import { CalendarDays, Copy, Layers3, Pencil, Power } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { ClassStatusBadge } from '@/components/classes/ClassStatusBadge';
import type { TurmaListada } from '@/types/classes.types';

interface Props { classes: TurmaListada[]; canManage: boolean; disabled: boolean; onEdit: (value: TurmaListada) => void; onClone: (value: TurmaListada) => void; onStatus: (value: TurmaListada) => void }
function date(value: string): string { const part = value.slice(0, 10).split('-'); return part.length === 3 ? `${part[2]}/${part[1]}/${part[0]}` : value; }

export function ClassesTable({ classes, canManage, disabled, onEdit, onClone, onStatus }: Props): JSX.Element {
  return <div className="overflow-x-auto"><table className="min-w-full border-collapse"><thead><tr className="border-b gm-border bg-slate-50/80 text-left"><th className="px-5 py-3.5 text-xs font-bold uppercase tracking-wide text-slate-500">Turma</th><th className="px-5 py-3.5 text-xs font-bold uppercase tracking-wide text-slate-500">Período</th><th className="px-5 py-3.5 text-xs font-bold uppercase tracking-wide text-slate-500">Módulos</th><th className="px-5 py-3.5 text-xs font-bold uppercase tracking-wide text-slate-500">Status</th>{canManage ? <th className="px-5 py-3.5 text-right text-xs font-bold uppercase tracking-wide text-slate-500">Ações</th> : null}</tr></thead><tbody>{classes.map((item) => <tr key={item.id} className={`border-b gm-border last:border-b-0 hover:bg-slate-50/60 ${item.ativo ? 'bg-white' : 'bg-slate-50/40'}`}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.ativo ? 'bg-blue-50 gm-text-primary' : 'bg-slate-100 text-slate-400'}`}><Layers3 className="h-5 w-5" /></div><div><p className="font-semibold text-slate-950">{item.codigo}</p><p className="mt-1 text-xs text-slate-500">{item.curso.nome}</p></div></div></td><td className="whitespace-nowrap px-5 py-4 text-sm text-slate-700"><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4 text-slate-400" />{date(item.dataInicio)} a {date(item.dataFim)}</span></td><td className="px-5 py-4 text-sm font-semibold text-slate-700">{item.quantidadeModulos}</td><td className="px-5 py-4"><ClassStatusBadge active={item.ativo} /></td>{canManage ? <td className="px-5 py-4"><div className="flex min-w-max justify-end gap-2"><Button type="button" variant="secondary" disabled={disabled} onClick={() => onEdit(item)}><Pencil className="h-4 w-4" />Editar</Button>{item.ativo ? <Button type="button" variant="secondary" disabled={disabled} onClick={() => onClone(item)}><Copy className="h-4 w-4" />Clonar</Button> : null}<Button type="button" variant={item.ativo ? 'danger' : 'primary'} disabled={disabled} onClick={() => onStatus(item)}><Power className="h-4 w-4" />{item.ativo ? 'Desativar' : 'Ativar'}</Button></div></td> : null}</tr>)}</tbody></table></div>;
}

export function ClassesTableSkeleton(): JSX.Element { return <div aria-label="Carregando turmas" aria-busy="true">{Array.from({ length: 6 }, (_, i) => <div key={i} className="h-20 animate-pulse border-b gm-border bg-slate-50 last:border-b-0" />)}</div>; }
